{% set name = "pip-tools" %}
{% set version = "6.1.0" %}
{% set sha256 = "400bf77e29cca48c31abc210042932bb52dcc138ef4ea4d52c5db429aa8ae6ee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - click

test:
  requires:
    - pip
  imports:
    - piptools
  commands:
    - pip check
    - pip-compile --help
    - pip-sync --help

about:
  home: https://github.com/jazzband/pip-tools
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE
  summary: pip-tools keeps your pinned dependencies fresh.
