{% set name = "pip-tools" %}
{% set version = "6.2.0" %}
{% set sha256 = "9ed38c73da4993e531694ea151f77048b4dbf2ba7b94c4a569daa39568cc6564" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - pip-compile = piptools.scripts.compile:cli
    - pip-sync = piptools.scripts.sync:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - click
    - pep517

test:
  requires:
    - pip
  imports:
    - piptools
  commands:
    - pip check
    - pip-compile --help
    - pip-sync --help

about:
  home: https://github.com/jazzband/pip-tools
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE
  summary: pip-tools keeps your pinned dependencies fresh.
